name: Change Daily Meal Plan PIN

on:
  schedule:
    - cron: '0 8 * * *'  # every day at 8 AM UTC
  workflow_dispatch:

jobs:
  change-pin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python & Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium

      - name: Run pin-change script
        env:
          STUDENT_ID: ${{ secrets.STUDENT_ID }}
        run: |
          python change_pin.py
